SmgMenuBundle:
    resource: "@SmgMenuBundle/Resources/config/routing.yml"
    prefix:   /

SmgPageBundle:
    resource: "@SmgPageBundle/Resources/config/routing.yml"
    prefix:   /

SmgNewsBundle:
    resource: "@SmgNewsBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
