SmgMenuBundle_homepage:
    pattern:  /helllo/{menu_name}
    defaults: { _controller: SmgMenuBundle:Render:simple }
SmgMenuBundle_item:
    resource: "@SmgMenuBundle/Resources/config/routing/item.yml"
    prefix:   /item
SmgMenuBundle_menu:
    resource: "@SmgMenuBundle/Resources/config/routing/menu.yml"
    prefix:   /menu
