SmgMenuBundle_item:
    resource: "@SmgMenuBundle/Resources/config/routing/item.yml"
    prefix:   /admin/item
SmgMenuBundle_menu:
    resource: "@SmgMenuBundle/Resources/config/routing/menu.yml"
    prefix:   /admin/menu