frontend_news:
    pattern:  /
    defaults: { _controller: "SmgNewsBundle:Frontend\\News:index" }

frontend_news_show:
    pattern:  /{id}/show
    defaults: { _controller: "SmgNewsBundle:Frontend\\News:show" }

