item_new:
    pattern:  /new/{menu_id}
    defaults: { _controller: "SmgMenuBundle:Item:new" }

item_create:
    pattern:  /create/{menu_id}
    defaults: { _controller: "SmgMenuBundle:Item:create" }
    requirements: { _method: post }

item_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SmgMenuBundle:Item:edit" }

item_update:
    pattern:  /{id}/update
    defaults: { _controller: "SmgMenuBundle:Item:update" }
    requirements: { _method: post }

item_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SmgMenuBundle:Item:delete" }