SmgNewsBundle_backend_news:
    resource: "@SmgNewsBundle/Resources/config/routing/backend_news.yml"
    prefix:   /admin/news
SmgNewsBundle_backend_comment:
    resource: "@SmgNewsBundle/Resources/config/routing/backend_comment.yml"
    prefix:   /admin/comment
SmgNewsBundle_frontend_news:
    resource: "@SmgNewsBundle/Resources/config/routing/frontend_news.yml"
    prefix:   /news
SmgNewsBundle_frontend_comment:
    resource: "@SmgNewsBundle/Resources/config/routing/frontend_comment.yml"
    prefix:   /comment